objects/Account.object
<CustomObject>
    <fields>
        <fullName>Core_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Core Dealer</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Customers (Core Dealer)</relationshipLabel>
        <relationshipName>Customers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Dealer_Abbreviation__c</fullName>
        <label>Dealer Abbreviation</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_City__c</fullName>
        <label>Dealer City</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Code__c</fullName>
        <label>Dealer Code</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Number__c</fullName>
        <label>Dealer Number</label>
        <length>5</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Town__c</fullName>
        <label>Dealer Town</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Dealer_Type__c</fullName>
        <label>Dealer Type</label>
        <picklist>
            <picklistValues>
                <fullName>Toyota – New Vehicles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toyota – Used Vehicles</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Signature Class</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Toyota - Parts &amp; Service</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lexus – L-Certified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lexus – Parts &amp; Service</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Email__c</fullName>
        <label>Email</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>Free_Phone__c</fullName>
        <label>Free Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Last_Touch_Point_Date__c</fullName>
        <label>Last Touch Point Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Touch_Point_From__c</fullName>
        <label>Last Touch Point From</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MapGrid_X__c</fullName>
        <label>MapGrid X</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MapGrid_Y__c</fullName>
        <label>MapGrid Y</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Inactive</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Receivership</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Toyota_Type__c</fullName>
        <label>Toyota Type</label>
        <picklist>
            <picklistValues>
                <fullName>Core Dealer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Dealer Branch</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Parts and Service Agent</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>N/A</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Dealership</fullName>
        <active>true</active>
        <label>Dealership</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Last_Touch_Point_Date__c</fullName>
        <label>Last Touch Point Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Touch_Point_From__c</fullName>
        <label>Last Touch Point From</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>MapGrid_X__c</fullName>
        <label>MapGrid X</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>MapGrid_Y__c</fullName>
        <label>MapGrid Y</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Simplicity_Dealer__c.object
<CustomObject>
    <fields>
        <fullName>AHContact1Cell__c</fullName>
        <label>AHContact1Cell</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>AHContact1Home__c</fullName>
        <label>AHContact1Home</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>AHContact1JobTitle__c</fullName>
        <label>AHContact1JobTitle</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AHContact1Name__c</fullName>
        <label>AHContact1Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AHContact2Cell__c</fullName>
        <label>AHContact2Cell</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>AHContact2Home__c</fullName>
        <label>AHContact2Home</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>AHContact2JobTitle__c</fullName>
        <label>AHContact2JobTitle</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AHContact2Name__c</fullName>
        <label>AHContact2Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AHContact3Cell__c</fullName>
        <label>AHContact3Cell</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>AHContact3Home__c</fullName>
        <label>AHContact3Home</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>AHContact3JobTitle__c</fullName>
        <label>AHContact3JobTitle</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AHContact3Name__c</fullName>
        <label>AHContact3Name</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Abbreviation__c</fullName>
        <label>Abbreviation</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Admin__c</fullName>
        <label>Admin</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Branch__c</fullName>
        <label>Branch</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>BusinessEmail__c</fullName>
        <label>BusinessEmail</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>CEO__c</fullName>
        <label>CEO</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CR__c</fullName>
        <label>CR</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>City__c</fullName>
        <label>City</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CompanyName__c</fullName>
        <label>CompanyName</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>CoreDealer__c</fullName>
        <label>CoreDealer</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerCode__c</fullName>
        <label>DealerCode</label>
        <length>3</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerCopyForSite__c</fullName>
        <label>DealerCopyForSite</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DealerType__c</fullName>
        <label>DealerType</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Extra_Care__c</fullName>
        <label>Extra Care</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>FaxBusiness__c</fullName>
        <label>FaxBusiness</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>FreePhone__c</fullName>
        <label>FreePhone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>NCCShortcodePhone_Local__c</fullName>
        <label>NCCShortcodePhone_Local</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>New_Sales__c</fullName>
        <label>New Sales</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Org_RSN__c</fullName>
        <label>Org RSN</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Parts__c</fullName>
        <label>Parts</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PhoneBusiness__c</fullName>
        <label>PhoneBusiness</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>PostalAddressLine1__c</fullName>
        <label>PostalAddressLine1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalAddressLine2__c</fullName>
        <label>PostalAddressLine2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalAddressLine3__c</fullName>
        <label>PostalAddressLine3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalAddressLine4__c</fullName>
        <label>PostalAddressLine4</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>PostalAddressPostCode__c</fullName>
        <label>PostalAddressPostCode</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Service__c</fullName>
        <label>Service</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetAddressLine1__c</fullName>
        <label>StreetAddressLine1</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetAddressLine2__c</fullName>
        <label>StreetAddressLine2</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetAddressLine3__c</fullName>
        <label>StreetAddressLine3</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>StreetAddressMapGrid_X__c</fullName>
        <label>StreetAddressMapGrid_X</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>StreetAddressMapGrid_Y__c</fullName>
        <label>StreetAddressMapGrid_Y</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Town__c</fullName>
        <label>Town</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Used_Sales__c</fullName>
        <label>Used Sales</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Website__c</fullName>
        <label>Website</label>
        <type>Url</type>
    </fields>
    <label>Simplicity Dealer</label>
    <nameField>
        <displayFormat>SD-{00000}</displayFormat>
        <label>Simplicity Dealer Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Simplicity Dealers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/LoadDealersBatchJob.cls
/*********************************************************************************
Name:           LoadDealersBatchJob
Author:         Digby Bartosh [Fujitsu]
Purpose:        This class is used to process the Cealer data from Simplicity
Created Date:   10/12/2016

Modification History:
<initials> - <date> - <reason for update>

********************************************************************************/
global class LoadDealersBatchJob implements Database.Batchable<sObject>{

    public String query;
    public String core;    
    public list<Account> updDealers  = new list<Account>();
    public list<Contact> updContacts  = new list<Contact>();
    public RecordType dealership = [select id from RecordType where name = 'Dealership' and SobjectType = 'Account' limit 1];
    
    // this method executes the query and returns the dealers data from simplicity
    global Database.querylocator start(Database.BatchableContext BC){
        system.debug(query);
        return Database.getQueryLocator(query);}

    // this method is the control method, and executes each of the individual process methods ========================================================================
    global void execute(Database.BatchableContext BC, List<sObject> scope){

        // process the records according to the mapping rules   
        for(sObject s : scope){Simplicity_Dealer__c ddata = (Simplicity_Dealer__c)s;   
                
                Account newDealer = new Account();

                 // simple data mappings              
                newDealer.Name = ddata.CompanyName__c;
                newDealer.Dealer_City__c = ddata.City__c;
                newDealer.Dealer_Town__c = ddata.Town__c;                               
                newDealer.Dealer_Abbreviation__c = ddata.Abbreviation__c;              
                newDealer.Dealer_Number__c = ddata.NCCShortcodePhone_Local__c;       
                newDealer.Dealer_Code__c = ddata.DealerCode__c;                               
                newDealer.Free_Phone__c = ddata.FreePhone__c;
                newDealer.Email__c = ddata.BusinessEmail__c;                           
                newDealer.Fax = ddata.FaxBusiness__c;                
                newDealer.Phone = ddata.PhoneBusiness__c;    
                newDealer.MapGrid_X__c = ddata.StreetAddressMapGrid_X__c;                               
                newDealer.MapGrid_Y__c = ddata.StreetAddressMapGrid_Y__c;
                newDealer.Status__c = 'Active';                                   
                newDealer.Type = 'Dealership';              
                newDealer.Website = ddata.Website__c;    
                if(ddata.CoreDealer__c == null) {newDealer.Toyota_Type__c='Core Dealer';}                               
                if(ddata.CoreDealer__c != null) {newDealer.Toyota_Type__c=' Dealer Branch';}   
                               
        		Pattern p = Pattern.compile('(CAB|DMJ|DNH|GEL|KAT|KUU|MOR|NPS|OMR|PAT|TMG|TOK|WAO|WAW|WNK|WSP)');
        		Matcher m = p.matcher(ddata.DealerCode__c); 
                if(m.find()) {newDealer.Toyota_Type__c=' Parts and Service Agent'; }                               
                               
                newDealer.Last_Touch_Point_From__c='Data load';
                newDealer.Last_Touch_Point_Date__c=Datetime.now();
                newDealer.RecordTypeId=dealership.Id;

				// lookup core dealer
                if(ddata.CoreDealer__c!=null){
                            List<Account> cDealer = [select id,name from Account where (name =:ddata.CoreDealer__c and toyota_type__c = 'Core Dealer')];
                            if(cDealer.size() > 0) {
                        		newDealer.Core_Dealer__c=cDealer[0].Id;
                    }
                 }
                               
                // Dealer type               
                newDealer.Dealer_Type__c=splitTypes(ddata);            
                               
                // postal address (billing)
                if(ddata.PostalAddressLine1__c != Null) {
                    		list<string> postadd = formatPostal(ddata);
                            newDealer.BillingStreet=postadd[0];
                    		newDealer.BillingCity=postadd[1];
                			newDealer.BillingPostalCode=ddata.PostalAddressPostCode__c;
                            newDealer.BillingCountry='New Zealand';                        
                }    
                               
                // Street address (billing)
                if(ddata.StreetAddressLine1__c != Null) {
                    		list<string> postadd = formatstreet(ddata);
                            newDealer.ShippingStreet=postadd[0];
                    		newDealer.ShippingCity=postadd[1];
                			newDealer.ShippingPostalCode=postadd[2];
                            newDealer.ShippingCountry='New Zealand';                        
                }   
                               
                updDealers.add(newDealer);               
  
                              
 		}
        
        system.debug(updDealers);
        upsert updDealers;
        System.debug('1.Number of Queries used in this apex code so far: ' + Limits.getQueries());
    }        

    // -------------------------------------------------------------------------------------------------------- UTILITY METHODS ----------------------------------------------------------------------------------------------------
 	// split up dealer types from simplicity field
    public  static String splitTypes(Simplicity_Dealer__c ddata) {
        			list<string> mspl = new list<string>();

        			list<string> dtypes = ddata.DealerType__c.split('\\?');
                    for(string dt: dtypes) {
                        if(dt.contains('Toyota')) {
                            if(dt.contains('New Vehicles')) {mspl.add('Toyota – New Vehicles');}
                            if(dt.contains('Used Vehicles')) {mspl.add('Toyota – Used Vehicles');}                                
                            if(dt.contains('Signature Class')) {mspl.add('Signature Class');}
                            if(dt.contains('Service / Parts')) {mspl.add('Toyota - Parts & Service');}                            
                        }
                        if(dt.contains('Lexus')) {
                            if(dt.contains('LCPO')) {mspl.add('Lexus – L-Certified');}
                            if(dt.contains('Service')) {mspl.add('Lexus – Parts & Service');}                                                        
                        }                        
        			}
        			
        			system.debug(mspl);
        			return String.join(mspl, ';');
    }        


 	// format the postal street address in the dealer table to a SFDC address
    public  static list<String> formatPostal(Simplicity_Dealer__c ddata) {
					list<string> street = new list<string>();

        			if(ddata.PostalAddressLine3__c != null) {
            			street.add(ddata.PostalAddressLine1__c + '\n' + ddata.PostalAddressLine2__c);
                        street.add(ddata.PostalAddressLine3__c.replace(ddata.PostalAddressPostCode__c, '').normalizeSpace());
                    } else {
            			street.add(ddata.PostalAddressLine1__c );
                        street.add(ddata.PostalAddressLine2__c.replace(ddata.PostalAddressPostCode__c, '').normalizeSpace());                       
                    }

        			return street;
    }
    
 	// format the  street address in the dealer table to a SFDC address
    public  static list<String> formatStreet(Simplicity_Dealer__c ddata) {
					list<string> street = new list<string>();
        			string postcode ='';

        			if(ddata.StreetAddressLine3__c != null) {
            			street.add(ddata.StreetAddressLine1__c + '\n' + ddata.StreetAddressLine2__c);
        				Pattern p = Pattern.compile('(\\b\\d{4}\\b)');
        				Matcher m = p.matcher(ddata.StreetAddressLine3__c); 
                        system.debug(ddata.StreetAddressLine3__c);
                        if(m.find()) {postcode = m.group(1); }
                        system.debug(postcode);                        
                        street.add(ddata.StreetAddressLine3__c.replace(postcode, '').normalizeSpace());
                        street.add(postcode);
                    } else {
            			street.add(ddata.StreetAddressLine1__c );
        				Pattern p = Pattern.compile('(\\b\\d{4}\\b)');
        				Matcher m = p.matcher(ddata.StreetAddressLine2__c); 
                        system.debug(ddata.StreetAddressLine2__c);
                        if(m.find()) {postcode = m.group(1); }
                        system.debug(postcode);                              
                        street.add(ddata.StreetAddressLine2__c.replace(postcode, '').normalizeSpace());
                        street.add(postcode);                                       
                    }

        			return street;
    }   
    
    
    // -------------------------------------------------------------------------------------------------------- FINISH METHOD ----------------------------------------------------------------------------------------------------    
    // this method is the completion process - this will send an email advising process complete 
    global void finish(Database.BatchableContext BC){
 			      
        if(Core == 'C') {
        
      		// process branch dealers
        	LoadDealersBatchJob ddata = new LoadDealersBatchJob();
        	ddata.core='B';
        	ddata.query = 'SELECT Id,Name,Abbreviation__c,Admin__c,AHContact1Cell__c,AHContact1Home__c,AHContact1JobTitle__c,AHContact1Name__c,' +
                'AHContact2Cell__c,AHContact2Home__c,AHContact2JobTitle__c,AHContact2Name__c,AHContact3Cell__c,AHContact3Home__c,AHContact3JobTitle__c,AHContact3Name__c,' +
                'Branch__c,BusinessEmail__c,CEO__c,City__c,CompanyName__c,CoreDealer__c,CR__c,DealerCode__c,DealerCopyForSite__c,DealerType__c,Extra_Care__c,' +                
                'FaxBusiness__c,FreePhone__c,NCCShortcodePhone_Local__c,New_Sales__c,Org_RSN__c,Parts__c,PhoneBusiness__c,' +     
                'PostalAddressLine1__c,PostalAddressLine2__c,PostalAddressLine3__c,PostalAddressLine4__c,PostalAddressPostCode__c,' +   
                'Service__c,StreetAddressLine1__c,StreetAddressLine2__c,StreetAddressLine3__c,StreetAddressMapGrid_X__c,StreetAddressMapGrid_Y__c,' +   
                'Town__c,Used_Sales__c,Website__c ' +   
                'FROM Simplicity_Dealer__c  where CoreDealer__c != null';
        	ID batchprocessid = Database.executeBatch(ddata);
        
        }
 			      
        if(Core == 'B') {
        
      		// process contacts for dealers
        	LoadDealersBatchContacts ddata = new LoadDealersBatchContacts();
        	ddata.core='N';
        	ddata.query = 'SELECT Id,Name,Abbreviation__c,Admin__c,AHContact1Cell__c,AHContact1Home__c,AHContact1JobTitle__c,AHContact1Name__c,' +
                'AHContact2Cell__c,AHContact2Home__c,AHContact2JobTitle__c,AHContact2Name__c,AHContact3Cell__c,AHContact3Home__c,AHContact3JobTitle__c,AHContact3Name__c,' +
                'Branch__c,BusinessEmail__c,CEO__c,City__c,CompanyName__c,CoreDealer__c,CR__c,DealerCode__c,DealerCopyForSite__c,DealerType__c,Extra_Care__c,' +                
                'FaxBusiness__c,FreePhone__c,NCCShortcodePhone_Local__c,New_Sales__c,Org_RSN__c,Parts__c,PhoneBusiness__c,' +     
                'PostalAddressLine1__c,PostalAddressLine2__c,PostalAddressLine3__c,PostalAddressLine4__c,PostalAddressPostCode__c,' +   
                'Service__c,StreetAddressLine1__c,StreetAddressLine2__c,StreetAddressLine3__c,StreetAddressMapGrid_X__c,StreetAddressMapGrid_Y__c,' +   
                'Town__c,Used_Sales__c,Website__c ' +   
                'FROM Simplicity_Dealer__c ';
        	ID batchprocessid = Database.executeBatch(ddata);
        
        }}
    
}