objects/ActivityLog__c.object
<CustomObject>
    <fields>
        <fullName>Account_Address__c</fullName>
        <label>Account Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Account_Industry__c</fullName>
        <label>Account Industry</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Name__c</fullName>
        <label>Account Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account_Phone__c</fullName>
        <label>Account Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>Account_Type__c</fullName>
        <label>Account Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipName>History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>History_Object__c</fullName>
        <label>History Object</label>
        <picklist>
            <picklistValues>
                <fullName>Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Vehicle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Plate</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ownership</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Modified_By__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Modified By</label>
        <referenceTo>User</referenceTo>
        <relationshipName>History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Modified_Date__c</fullName>
        <label>Modified Date</label>
        <type>DateTime</type>
    </fields>
    <label>Activity Log</label>
    <nameField>
        <label>Activity Log Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Activity Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/AccountActivityLog.cls
/*********************************************************************************
Name:           AccountActivityLog
Author:         Digby Bartosh [Fujitsu]
Purpose:        This class is used to track field history on the Account Records.
Created Date:   24/10/2016

Modification History:
<initials> - <date> - <reason for update>

********************************************************************************/
public class AccountActivityLog {
   
        public static void recordFieldChanges(Map<ID,SObject> oldRecordMap, Map<ID,SObject> newRecordMap, Boolean rcdInsert, Boolean rcdUpdate){
        system.debug(newRecordMap);
        string[] objectName = new string[]{string.valueOf(oldRecordMap.getSObjectType())};
        List<ActivityLog__c> fieldChanges = new List<ActivityLog__c>();
         
        for(ID recordID:newRecordMap.keySet()){
            SObject myNewRecord = newRecordMap.get(recordID);
            SObject myOldRecord = oldRecordMap.get(recordID);
            ActivityLog__c  afh = new ActivityLog__c ();

            if (rcdInsert) afh.Name = 'Account Created';
            if (rcdUpdate) afh.Name = 'Account Updated';
            if(myNewRecord.get('Name') != myOldRecord.get('Name')) afh.Account_Name__c = String.valueOf(myNewRecord.get('Name'));
            if(myNewRecord.get('Type') != myOldRecord.get('Type')) afh.Account_Type__c = String.valueOf(myNewRecord.get('Type'));
            if(myNewRecord.get('Phone') != myOldRecord.get('Phone')) afh.Account_Phone__c = String.valueOf(myNewRecord.get('Phone'));
            if(myNewRecord.get('Industry') != myOldRecord.get('Industry')) afh.Account_Industry__c = String.valueOf(myNewRecord.get('Industry'));
            if(myNewRecord.get('BillingAddress') != myOldRecord.get('BillingAddress')) afh.Account_Address__c = String.valueOf(myNewRecord.get('BillingAddress'));
            afh.History_Object__c='Account';
            afh.Account__c = recordID;
            afh.Modified_Date__c = Datetime.now();
			afh.Modified_By__c = UserInfo.getUserId();
 			fieldChanges.add(afh);
        }
       insert fieldChanges;
 
    }

}