objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Driver_Licence_Number__c</fullName>
        <label>Driver Licence Number</label>
        <length>9</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Roles__c</fullName>
        <label>Roles</label>
        <picklist>
            <picklistValues>
                <fullName>Marketing</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Driver</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Owner</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VIP</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>MultiselectPicklist</type>
    </fields>
    <fields>
        <fullName>Toyota_PMA_Dealer__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Toyota PMA Dealer</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>Account.Type</field>
                <operation>equals</operation>
                <value>Dealership</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Contacts</relationshipLabel>
        <relationshipName>Contacts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

objects/Ownership__c.object
<CustomObject>
    <fields>
        <fullName>Registered_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Registered Owner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ownerships</relationshipLabel>
        <relationshipName>Ownerships</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Ownerships</relationshipLabel>
        <relationshipName>Ownerships</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ownership</label>
    <nameField>
        <displayFormat>O-{00000000}</displayFormat>
        <label>Ownership Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ownerships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Ownership_History__c.object
<CustomObject>
    <fields>
        <fullName>Registered_Owner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Registered Owner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Ownerships History</relationshipLabel>
        <relationshipName>Ownerships_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Ownerships History</relationshipLabel>
        <relationshipName>Ownerships_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Ownership History</label>
    <nameField>
        <displayFormat>OH-{00000000}</displayFormat>
        <label>Ownership History</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Ownerships History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Plate__c.object
<CustomObject>
    <label>Plate</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Plate_History__c.object
<CustomObject>
    <fields>
        <fullName>Plate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plate</label>
        <referenceTo>Plate__c</referenceTo>
        <relationshipLabel>Plates History</relationshipLabel>
        <relationshipName>Plates_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Plates History</relationshipLabel>
        <relationshipName>Plates_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plate History</label>
    <nameField>
        <displayFormat>PH-{00000000}</displayFormat>
        <label>Plate History</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plates History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Registration_Active_Plate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Registration Active Plate</label>
        <referenceTo>Plate__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/RelatedListController.cls
/*********************************************************************************
Name:       RelatedListController
Author:     Himanshu Verma [Fujitsu]
Purpose:    It has various method to fetch the list of child records on the basis of parentReord
Created Date:   29/12/2016

Modification History:
<initials> - <date> - <reason for update>

********************************************************************************/


public class RelatedListController{


     @AuraEnabled
     public static list<sobject> fetchPreviousOwners(string recordId){
     
            string query = FieldsUtility.fetchAllFields('Ownership_History__c');
            query += ' where Vehicle__c= \''+recordId+'\'';
            list<sobject> sobjectList = Database.query(query);
            system.debug('###sobjectListsize'+sobjectList.size());
            return sobjectList ;
     
     }
    
     @AuraEnabled
     public static list<sobject> fetchCurrentOwners(string recordId){
     
            string query = FieldsUtility.fetchAllFields('Ownership__c');
            query += ' where Vehicle__c= \''+recordId+'\'';
            list<sobject> sobjectList = Database.query(query);
            system.debug('###sobjectListsize'+sobjectList.size());
            return sobjectList ;
     
     }

     @AuraEnabled
     public static list<sobject> fetchPreviousVehicles(string recordId){
     
            string query = FieldsUtility.fetchAllFields('Ownership_History__c');
            query += ' where Registered_Owner__c= \''+recordId+'\'';
            list<sobject> sobjectList = Database.query(query);
            system.debug('###sobjectListsize'+sobjectList.size());
            return sobjectList ;
     
     }
    
     @AuraEnabled
     public static list<sobject> fetchCurrentVehicles(string recordId){
     
            string query = FieldsUtility.fetchAllFields('Ownership__c');
            query += ' where Registered_Owner__c= \''+recordId+'\'';
            list<sobject> sobjectList = Database.query(query);
            system.debug('###sobjectListsize'+sobjectList.size());
            return sobjectList ;
     
     }

     @AuraEnabled
     public static list<sobject> fetchContacts(string recordId){
     
            string query = 'Select Id,Name,Title,OtherCity,Toyota_PMA_Dealer__c,Phone,MobilePhone,Email,Driver_Licence_Number__c,Roles__c  from Contact ';
            query += ' where AccountId= \''+recordId+'\'';
            list<sobject> sobjectList = Database.query(query);
            system.debug('###sobjectListsize'+sobjectList.size());
            return sobjectList ;
     
     }    

     @AuraEnabled
     public static list<sobject> fetchPlateVehicleCurrent(string recordId){
     
            string query = FieldsUtility.fetchAllFields('Vehicle__c');
            query += ' where Registration_Active_Plate__c= \''+recordId+'\'';
            list<sobject> sobjectList = Database.query(query);
            system.debug('###sobjectListsize'+sobjectList.size());
            return sobjectList ;
     
     }
     @AuraEnabled
     public static list<sobject> fetchPlateVehicleHistory(string recordId){
     
            string query = FieldsUtility.fetchAllFields('Plate_History__c');
            query += ' where Plate__c= \''+recordId+'\'';
            list<sobject> sobjectList = Database.query(query);
            system.debug('###sobjectListsize'+sobjectList.size());
            return sobjectList ;
     
     }
    
     @AuraEnabled
    public static list<sobject> fetchFieldHistory(String objId,String objectName){
          
          string query ='Select Id ,(Select OldValue, NewValue, Field, CreatedById,createdby.name,CreatedDate from histories Order by CreatedDate DESC) ';
          query += 'from '+objectName +' where Id = \''+objId+'\'';
          sobject obj = Database.query(query);
          list<sobject> sobjectList= obj.getSobjects('Histories');
          return  sobjectList; 
    }
    
    @AuraEnabled
    public static list<sobject> fetchVehicalPlateHistory(string recordId){
          
         string query = FieldsUtility.fetchAllFields('Plate_History__c');
         query += ' where Vehicle__c= \''+recordId+'\'';
         list<sobject> sobjectList = Database.query(query);
         system.debug('###sobjectListsize'+sobjectList.size());
         return sobjectList ;
    }


}