objects/Plate__c.object
<CustomObject>
    <fields>
        <fullName>Plate_Type__c</fullName>
        <label>Plate Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Crown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diplomatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personalised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plate</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Plate_History__c.object
<CustomObject>
    <fields>
        <fullName>Plate_Type__c</fullName>
        <label>Plate Type</label>
        <picklist>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crown</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Diplomatic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Investment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Personalised</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Special Issue</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Trade</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Plate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Plate</label>
        <referenceTo>Plate__c</referenceTo>
        <relationshipLabel>Plates History</relationshipLabel>
        <relationshipName>Plates_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registration_Plate__c</fullName>
        <formula>Plate__r.Registration_Plate_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Registration Plate</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Plates History</relationshipLabel>
        <relationshipName>Plates_History</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Plate History</label>
    <nameField>
        <displayFormat>PH-{00000000}</displayFormat>
        <label>Plate History</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plates History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/platehistoryDemo.cls
public class platehistoryDemo{

   @AuraEnabled
   
   public static list<Plate_History__c> getPlateHistories(string vehicalId){
   
          list<Plate_History__c> platehistory=[select id,createddate,name,Plate__c,
                                               Plate_Type__c,Registration_Plate__c,Vehicle__c
                                               from Plate_History__c where Vehicle__c=:vehicalId];
                                               
          return  platehistory;
   }




}