objects/Plate__c.object
<CustomObject>
    <fields>
        <fullName>Last_Touch_Point_Date__c</fullName>
        <label>Last Touch Point Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Touch_Point_From__c</fullName>
        <label>Last Touch Point From</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Plate_Number__c</fullName>
        <externalId>true</externalId>
        <label>Registration Plate Number</label>
        <length>10</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>Registration_Status__c</fullName>
        <label>Registration Status</label>
        <picklist>
            <picklistValues>
                <fullName>Active</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Cancelled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lapsed</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Plate</label>
    <nameField>
        <displayFormat>RP-{000000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Plates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Recall_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Bulletin_Link__c</fullName>
        <label>Bulletin Link</label>
        <type>Url</type>
    </fields>
    <fields>
        <fullName>Bulletin_Reference__c</fullName>
        <label>Bulletin Reference</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Description__c</fullName>
        <label>Campaign Description</label>
        <length>70</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Prefix__c</fullName>
        <label>Campaign Prefix</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Reference__c</fullName>
        <label>Campaign Reference</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Campaign_Start_Date__c</fullName>
        <label>Campaign Start Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Campaign_Status__c</fullName>
        <label>Campaign Status</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Cause__c</fullName>
        <label>Cause</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Condition__c</fullName>
        <label>Condition</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Covering_Letter_Reference__c</fullName>
        <label>Covering Letter Reference</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Recall_Vehicle__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Recall Vehicle</label>
        <referenceTo>Vehicle__c</referenceTo>
        <relationshipLabel>Recall Campaigns</relationshipLabel>
        <relationshipName>Recall_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Remedy__c</fullName>
        <label>Remedy</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>Recall Campaign</label>
    <nameField>
        <displayFormat>RC-{0000000}</displayFormat>
        <label>Recall Campaign Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Recall Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

objects/Vehicle__c.object
<CustomObject>
    <fields>
        <fullName>Body_Style__c</fullName>
        <label>Body Style</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Chassis_Number__c</fullName>
        <label>Chassis Number</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Date_First_Registered_in_NZ__c</fullName>
        <label>Date First Registered in NZ</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Engine_Number__c</fullName>
        <label>Engine Number</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Engine_Size__c</fullName>
        <label>Engine Size</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Fuel_Type__c</fullName>
        <label>Fuel Type</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Full_Photo_Id__c</fullName>
        <label>Full Photo Id</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Key_Number_Codes__c</fullName>
        <label>Key Number Codes</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Last_Touch_Point_Date__c</fullName>
        <label>Last Touch Point Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Last_Touch_Point_From__c</fullName>
        <label>Last Touch Point From</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Code__c</fullName>
        <label>Model Code</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Variant_Group_Name__c</fullName>
        <label>Model Variant Group Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Model_Variant_Name__c</fullName>
        <label>Model Variant Name</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Doors__c</fullName>
        <label>Number of Doors</label>
        <picklist>
            <picklistValues>
                <fullName>2</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>4</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>5</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Number_of_Gears__c</fullName>
        <label>Number of Gears</label>
        <length>2</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Number_of_Seats__c</fullName>
        <label>Number of Seats</label>
        <precision>2</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Odometer_Reading_Date__c</fullName>
        <label>Odometer Reading Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Odometer_Readings__c</fullName>
        <label>Odometer Readings</label>
        <length>22</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <label>Product Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Product_SubCode__c</fullName>
        <label>Product Sub Code</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Registration_Active_Plate__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Registration Active Plate</label>
        <referenceTo>Plate__c</referenceTo>
        <relationshipLabel>Vehicles</relationshipLabel>
        <relationshipName>Vehicles</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Registration_Plate_Number__c</fullName>
        <formula>Registration_Active_Plate__r.Registration_Plate_Number__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Registration Plate Number</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Transmission__c</fullName>
        <label>Transmission</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Unit_Number__c</fullName>
        <label>Unit Number</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>VIN__c</fullName>
        <label>VIN</label>
        <length>17</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <fields>
        <fullName>VMS_GUID__c</fullName>
        <label>VMS GUID</label>
        <length>40</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Colours__c</fullName>
        <label>Vehicle Colours</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Make__c</fullName>
        <label>Vehicle Make</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Vehicle_Model__c</fullName>
        <label>Vehicle Model</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Year_Made__c</fullName>
        <label>Year Made</label>
        <length>4</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>thumbId__c</fullName>
        <description>id for thumbnail picture</description>
        <label>thumbId</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <label>Vehicle</label>
    <nameField>
        <displayFormat>V-{000000}</displayFormat>
        <label>Vehicle Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Vehicles</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

classes/DataHubTestServiceClass.cls
/*********************************************************************************
Name:          DataHubTestServiceClass
Author:         Digby Bartosh [Fujitsu]
Purpose:        This class is used to access VehicleInformation from Toyota's DataHub
Created Date:   12/11/2016

Modification History:
<initials> - <date> - <reason for update>

********************************************************************************/
public class DataHubTestServiceClass {
    
    	 id vID;
    
    	// ------------------------------------------------------------------------------------------------------ callout methods -----------------------------------------------------------------------------------------------------------------------------------------------------            
    	// fetch the data based on Plate
        public  void fetchDataHubPlate(string plate){

            // call datahub and get vehicle details
            VMSgetVehicleInfoInterface.wrapperClass wc = new VMSgetVehicleInfoInterface.wrapperClass();
            VMSgetVehicleInfoInterface run = new VMSgetVehicleInfoInterface();
			wc=run.getCallout(plate);
            
            // call datahub and get the vehicle photo
            VMSgetVehiclePhotoInterface.wrapperClass wcp = new VMSgetVehiclePhotoInterface.wrapperClass();	
            if(!wc.Error && wc.VMSGUID != null) {
				VMSgetVehiclePhotoInterface runp = new VMSgetVehiclePhotoInterface();
                wcp=runp.getCallout(wc.VMSGUID);      
            }   
            
            // call datahub and get the vehicle recalls
            list<VMSVehicleRecallInterface.wrapperClass> wcr = new list<VMSVehicleRecallInterface.wrapperClass>();	
            if(!wc.Error && wc.VIN != null) {
				VMSVehicleRecallInterface runr = new VMSVehicleRecallInterface();
                wcr=runr.getCallout(wc.VIN);      
            }   
            
            // update vehicle table based on responses from datahub
            if(!wc.Error) {updateVehicleData(wc);}
            if(!wcp.Error) {updateVehiclePHOTO(wcp);}            
            if(!wcr[0].Error) {updateVehicleRecalls(wcr);}    
    		}
        
    	// fetch the data based on VIN
        public  void fetchDataHubVIN(string vin){

            // call datahub and get vehicle details
            VMSgetVehicleInfoInterface.wrapperClass wc = new VMSgetVehicleInfoInterface.wrapperClass();
            VMSgetVehicleInfoInterface run = new VMSgetVehicleInfoInterface();
			wc=run.getCalloutVIN(vin);
            
            // call datahub and get the vehicle photo
            VMSgetVehiclePhotoInterface.wrapperClass wcp = new VMSgetVehiclePhotoInterface.wrapperClass();	
            if(!wc.Error && wc.VMSGUID != null) {
				VMSgetVehiclePhotoInterface runp = new VMSgetVehiclePhotoInterface();
                wcp=runp.getCallout(wc.VMSGUID);      
            }   
            
            // call datahub and get the vehicle recalls
            list<VMSVehicleRecallInterface.wrapperClass> wcr = new list<VMSVehicleRecallInterface.wrapperClass>();	
            if(!wc.Error && wc.VIN != null) {
				VMSVehicleRecallInterface runr = new VMSVehicleRecallInterface();
                wcr=runr.getCallout(wc.VIN);      
            }   
            
            // update vehicle table based on responses from datahub
            if(!wc.Error) {updateVehicleData(wc);}
            if(!wcp.Error) {updateVehiclePHOTO(wcp);}            
            if(!wcr[0].Error) {updateVehicleRecalls(wcr);}    
    		}
    
    
    	// ------------------------------------------------------------------------------------------------------  process responses -----------------------------------------------------------------------------------------------------------------------------------------------------                
    	// check the vehicle table and update the data based on datahub
    	public void updateVehicleData(VMSgetVehicleInfoInterface.wrapperClass datahubData) {
        
            date odoreading = Date.newInstance(1,1,1);
            
            // get any existing vehicle record and update if it exists
            Vehicle__c newVehicle = new Vehicle__c();
            id vehicleID = null;
        	list<Vehicle__c> listVecs = [select id,name,VIN__c,Odometer_Reading_Date__c  from Vehicle__c where Vin__c = :datahubData.VIN];
            if(!listVecs.isEmpty()) { 
                vehicleID = listVecs[0].Id; 
                odoreading = listVecs[0].Odometer_Reading_Date__c; 
            }
            
            // check plate record and add one if it doesnt exist.
        	list<Plate__c> listPlates = [select id,name,Registration_Plate_Number__c from Plate__c where (Registration_Plate_Number__c = :datahubData.Registration)];
            if(!listPlates.isEmpty()) { newVehicle.Registration_Active_Plate__c = listPlates[0].Id; }       
            if(listPlates.isEmpty()) { 
                Plate__c plate = new Plate__c(Registration_Plate_Number__c=datahubData.Registration, Registration_Status__c = 'Active');
    				insert plate;
                	newVehicle.Registration_Active_Plate__c = plate.Id;
            }            

            // map data from datahub to vehicle table.
            newVehicle.ID = vehicleID;
            
            // Core details - check and if different set a message that its been updated.
            if(datahubdata.VIN != null) {newVehicle.VIN__c=datahubData.VIN;  }
            if(datahubdata.FrameID != null) {newVehicle.Chassis_Number__c=datahubData.FrameID; }
            if(datahubdata.DateFirstRegisteredinNZ != null) {newVehicle.Date_First_Registered_in_NZ__c = datahubData.DateFirstRegisteredinNZ;   }         
            if(datahubdata.YearMade != null) {newVehicle.Year_Made__c = datahubData.YearMade;        }            
            if(datahubdata.product != null) {newVehicle.Product_Code__c=datahubData.product; }
            if(datahubdata.subproduct != null) {newVehicle.Product_SubCode__c=datahubData.subproduct;       }
            if(datahubdata.MarqueName != null) {newVehicle.Vehicle_Make__c=datahubData.MarqueName; }
            if(datahubdata.ModelRangeName != null) {newVehicle.Vehicle_Model__c=datahubData.ModelRangeName; }
            if(datahubdata.ModelVariantGroupName != null) {newVehicle.Model_Variant_Group_Name__c=datahubData.ModelVariantGroupName; }
            if(datahubdata.ModelVariantName != null) {newVehicle.Model_Variant_Name__c=datahubData.ModelVariantName; }
            if(datahubdata.ModelCode != null) {newVehicle.Model_Code__c=datahubData.ModelCode;  }
            
            // Dynamic details
            if(datahubdata.ReadingDate != null) {
                if(datahubdata.ReadingDate > odoreading) {
                        if(datahubdata.odometerReading != null) {newVehicle.Odometer_Readings__c = datahubData.odometerReading; }
                        newVehicle.Odometer_Reading_Date__c = datahubData.ReadingDate;               
                }
            }
            
            // Periphial details
            if(datahubdata.VMSGUID != null) {newVehicle.VMS_GUID__c = datahubData.VMSGUID;  }
            if(datahubdata.ManualAutoIndicator != null) {newVehicle.Transmission__c=datahubData.ManualAutoIndicator; }
            if(datahubdata.NumberofGears != null) {newVehicle.Number_of_Gears__c=datahubData.NumberofGears; }
            if(datahubdata.NumberofDoors != null) {newVehicle.Number_of_Doors__c=datahubData.NumberofDoors; }               
            if(datahubdata.NumberofSeats != null) {newVehicle.Number_of_Seats__c=datahubData.NumberofSeats; }
            if(datahubdata.BodyShape != null) {newVehicle.Body_Style__c=datahubData.BodyShape; }            
            if(datahubdata.ColourName != null) {newVehicle.Vehicle_Colours__c=datahubData.ColourName; }            
            if(datahubdata.Fuel != null) {newVehicle.Fuel_Type__c=datahubData.Fuel; }            
            if(datahubdata.EngineCapacity != null) {newVehicle.Engine_Size__c=datahubData.EngineCapacity; }
            if(datahubdata.EngineNumber != null) {newVehicle.Engine_Number__c=datahubData.EngineNumber; }
            if(datahubdata.KeyNumber != null) {newVehicle.Key_Number_Codes__c=datahubData.KeyNumber; }
            if(datahubdata.UnitNumber != null) {newVehicle.Unit_Number__c=datahubData.UnitNumber;  }

            newVehicle.Last_Touch_Point_Date__c=Datetime.now();
            newVehicle.Last_Touch_Point_From__c='VMS';
            upsert newVehicle;
            vID = newVehicle.Id;

    }
    
        
    	// check the vehicle table with the photoo from datahub
    	public void updateVehiclePHOTO(VMSgetVehiclePhotoInterface.wrapperClass pic) {
    
            // get any existing vehicle record and update if it exists
            Vehicle__c newVehicle = new Vehicle__c();
        	list<Vehicle__c> listVecs = [select id,name,VIN__c,thumbId__c from Vehicle__c where Id = :vID];
            for(Vehicle__c vDets: listVecs) {
            
            Attachment newPhoto = new Attachment();
            try {newPhoto.Name = pic.imagetypename + ' - ' + pic.filename; }  catch(Exception e) {}
            if(pic.data != null) {newPhoto.body =  encodingUtil.base64Decode(pic.data);}
            if(pic.format != null) {newPhoto.ContentType=pic.format;}
            newPhoto.ParentId=vID;
                
            list<Attachment> aPhoto = [select id from Attachment where (ParentID=:vID and Name = :newPhoto.Name)];
            if(!aPhoto.isEmpty()) { newPhoto.Id = aPhoto[0].Id; }  
            upsert newPhoto;
                
            If(pic.imagetypename == 'FULL') {vDets.thumbId__c = newPhoto.Id;}
            If(pic.imagetypename == 'Full') {vDets.Full_Photo_ID__c = newPhoto.Id;}                  
     		upsert vDets;              
            }

        }
        
    	// update the recall campaigns table with data from datahub
    	public void updateVehicleRecalls(list<VMSVehicleRecallInterface.wrapperClass> recalls) {

            list<Recall_Campaign__c> newRecalls = new list<Recall_Campaign__c>();
            
            // get any existing recall record and update if it exists
            for(VMSVehicleRecallInterface.wrapperClass recall: recalls) {
            	
                Recall_Campaign__c newRecall = new Recall_Campaign__c();     
                if(recall.campaignprefix != null) {newRecall.Campaign_Prefix__c = recall.campaignprefix;}
                if(recall.campaignreference != null) {newRecall.Campaign_Reference__c = recall.campaignreference;}
                if(recall.campaigndescription != null) {newRecall.Campaign_Description__c = recall.campaigndescription;}
                if(recall.campaignstatus != null) {newRecall.Campaign_Status__c = recall.campaignstatus;}
                if(recall.bulletinlink != null) {newRecall.Bulletin_Link__c = EncodingUtil.urlDecode(recall.bulletinlink, 'UTF-8'); }
                if(recall.bulletingreference != null) {newRecall.Bulletin_Reference__c = recall.bulletingreference;}
                if(recall.campaignstartdate != null) {newRecall.Campaign_Start_Date__c = recall.campaignstartdate;}
                if(recall.cause != null) {newRecall.Cause__c = recall.cause;}
                if(recall.condition != null) {newRecall.Condition__c = recall.condition;}
                if(recall.remedy != null) {newRecall.Remedy__c = recall.remedy;}
                if(recall.coveringletterreference != null) {newRecall.Covering_Letter_Reference__c = recall.coveringletterreference;}
				newRecall.Recall_Vehicle__c = vId;
                
                list<Recall_Campaign__c> rDets = [select id from Recall_Campaign__c where (Recall_Vehicle__c = :vId and Campaign_Prefix__c = :recall.campaignprefix and Campaign_Reference__c = :recall.campaignreference) limit 1];
                    if(!rDets.isEmpty()) {newRecall.Id = rDets[0].Id; }
                
     			newRecalls.add(newRecall);              
            }  
			upsert newRecalls; 
        }
    
}